services:
  iot-monitor:
    image: alexswilliams/homepower:master--2025-05-02-23-42--b445491
    volumes:
      - "./config/homepower/devices.yaml:/etc/homepower/devices.yaml"
      - "./config/homepower/credentials.yaml:/etc/homepower/credentials.yaml"
    environment:
      - HOMEPOWER_DEVICE_CONFIG_FILEPATH=/etc/homepower/devices.yaml
      - HOMEPOWER_CREDENTIAL_FILEPATH=/etc/homepower/credentials.yaml
    restart: always
    read_only: true
    logging:
      driver: "local"
      options:
        max-size: "1m"
        max-file: "3"
    ports:
      - "9981:9981"

  prom-trmnl-renderer:
    image: alexswilliams/prom-trmnl-renderer:master--2025-06-20-20-44--d2f074d
    volumes:
      - "./config/prom-trmnl-renderer/credentials.yaml:/var/aws/credentials"
    environment:
      - BUCKET_NAME=applied-quickness-bubble-trmnl-export
      - CREDENTIAL_FILENAME=/var/aws/credentials
      - PROMETHEUS_URI=http://prometheus:9090
    restart: always
    read_only: true
    logging:
      driver: "local"
      options:
        max-size: "1m"
        max-file: "3"

  govee-monitor:
    image: alexswilliams/govee-prometheus:master--2025-02-22-03-22--4329f7b
    restart: always
    read_only: true
    logging:
      driver: "local"
      options:
        max-size: "1m"
        max-file: "3"
    volumes:
      - "./config/govee/devices.csv:/etc/govee/devices.csv"
    environment:
      - "BT_ALIASES_FILE_PATH=/etc/govee/devices.csv"
      # - "BLE_SCAN_INTERVAL=53"
      # - "BLE_SCAN_WINDOW=17"
      - "BLE_IGNORE_DUPLICATES=false"
      - "VERBOSE=false"
      - "METRIC_TTL_SECONDS=110"
    network_mode: host # exposes port 8080

  telegraf:
    # https://hub.docker.com/_/telegraf/tags
    image: telegraf:1.34.2
    restart: always
    read_only: true
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "9273:9273"
    cap_add:
      - NET_RAW
    volumes:
      - "./config/telegraf.conf:/etc/telegraf/telegraf.conf"
      - "./config/mibs:/root/.snmp/mibs"
      - "/usr/share/snmp/mibs:/usr/share/snmp/mibs"

  alertmanager:
    # https://hub.docker.com/r/prom/alertmanager/tags
    image: prom/alertmanager:v0.28.1
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    volumes:
      - "./config/alertmanager:/etc/alertmanager/config"
      - "/mnt/data/alertmanager/data:/etc/alertmanager/data"
    command:
      - "--config.file=/etc/alertmanager/config/alertmanager.yml"
      - "--web.listen-address=:9093"
      - "--web.external-url=http://192.168.1.5:9093"
      # - "--log.level=debug"
    expose:
      - "9093"
    ports:
      - "9093:9093"

  prometheus:
    # https://hub.docker.com/r/prom/prometheus/tags
    image: prom/prometheus:v3.3.1
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    volumes:
      - "./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./config/prometheus/rules.yml:/etc/prometheus/rules.yml"
      - "/mnt/data/prometheus/data:/etc/prometheus/data"
    command:
      - "--storage.tsdb.retention.time=5y"
      - "--storage.tsdb.retention.size=28GB"
      - "--storage.tsdb.path=/etc/prometheus/data"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
      - "--web.external-url=http://192.168.1.5:9090"
    expose:
      - "9090"
    ports:
      - "9090:9090"

  grafana:
    # https://hub.docker.com/r/grafana/grafana/tags
    image: grafana/grafana:11.6.1
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    volumes:
      - "./config/grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./config/grafana/grafana-datasources/:/etc/grafana/provisioning/datasources"
      - "/mnt/data/grafana:/var/lib/grafana"
    expose:
      - "3000"
    ports:
      - "3000:3000"

  prom-node-exporter:
    # https://hub.docker.com/r/prom/node-exporter/tags
    image: prom/node-exporter:v1.9.1
    restart: always
    user: root
    privileged: true
    read_only: true
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    pid: host
    volumes:
      - "/proc:/host/proc:ro"
      - "/:/host/root:ro,rslave"
      - "/sys:/host/sys:ro"
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/host/root"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(host/root/)?(dev|proc|sys|run|var/lib/docker/.+)"
      - "--web.listen-address=:9100"
      - "--web.disable-exporter-metrics"
    expose:
      - "9100"
    ports:
      - "9100:9100"
