version: '3.8'
services:

  telegraf:
    image: telegraf:1.23.2
    restart: always
    read_only: true
    ports:
      - "9273:9273"
    cap_add:
      - NET_RAW
    volumes:
      - "./config/telegraf.conf:/etc/telegraf/telegraf.conf"
      - "./config/mibs:/root/.snmp/mibs"
      - "/usr/share/snmp/mibs:/usr/share/snmp/mibs"


  prometheus:
    image: prom/prometheus:v2.37.0
    restart: always
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus-volume:/etc/prometheus/data"
    command:
      - "--storage.tsdb.retention.time=3y"
      - "--storage.tsdb.retention.size=16GB"
      - "--config.file=/etc/prometheus/prometheus.yml"
    expose:
      - "9090"
    ports:
      - "9090:9090"

  prom-node-exporter:
    image: prom/node-exporter:v1.3.1
    restart: always
    user: root
    privileged: true
    read_only: true
    pid: host
    volumes:
      - "/proc:/host/proc:ro"
      - "/:/host/root:ro,rslave"
      - "/sys:/host/sys:ro"
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/host/root"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(host/root/)?(dev|proc|sys|run|var/lib/docker/.+)"
      - "--web.listen-address=:9100"
      - "--web.disable-exporter-metrics"
    expose:
      - "9100"
    ports:
      - "9100:9100"

volumes:
  prometheus-volume:

