version: '3.8'
services:

  iot-monitor:
    image: alexswilliams/homepower:master--2023-12-05-01-57--048c481
    volumes:
      - "./config/homepower/devices.yaml:/etc/homepower/devices.yaml"
      - "./config/homepower/credentials.yaml:/etc/homepower/credentials.yaml"
    environment:
      - HOMEPOWER_DEVICE_CONFIG_FILEPATH=/etc/homepower/devices.yaml
      - HOMEPOWER_CREDENTIAL_FILEPATH=/etc/homepower/credentials.yaml
    restart: always
    read_only: true
    ports:
      - "9981:9981"

  govee-monitor:
    image: alexswilliams/govee-prometheus:master--2023-12-30-18-29--38fe866
    restart: always
    read_only: true
    volumes:
      - "./config/govee/devices.csv:/etc/govee/devices.csv"
    environment:
      - "BT_ALIASES=/etc/govee/devices.csv"
    network_mode: host # exposes port 8080

  telegraf:
    image: telegraf:1.28.5
    restart: always
    read_only: true
    ports:
      - "9273:9273"
    cap_add:
      - NET_RAW
    volumes:
      - "./config/telegraf.conf:/etc/telegraf/telegraf.conf"
      - "./config/mibs:/root/.snmp/mibs"
      - "/usr/share/snmp/mibs:/usr/share/snmp/mibs"

  prometheus:
    image: prom/prometheus:v2.48.0
    restart: always
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus-volume:/etc/prometheus/data"
    command:
      - "--storage.tsdb.retention.time=3y"
      - "--storage.tsdb.retention.size=16GB"
      - "--config.file=/etc/prometheus/prometheus.yml"
    expose:
      - "9090"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.2.2
    restart: always
    volumes:
      - "./config/grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./config/grafana/grafana-datasources/:/etc/grafana/provisioning/datasources"
      - "grafana-volume:/var/lib/grafana"
    expose:
      - "3000"
    ports:
      - "3000:3000"

  prom-node-exporter:
    image: prom/node-exporter:v1.7.0
    restart: always
    user: root
    privileged: true
    read_only: true
    pid: host
    volumes:
      - "/proc:/host/proc:ro"
      - "/:/host/root:ro,rslave"
      - "/sys:/host/sys:ro"
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/host/root"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(host/root/)?(dev|proc|sys|run|var/lib/docker/.+)"
      - "--web.listen-address=:9100"
      - "--web.disable-exporter-metrics"
    expose:
      - "9100"
    ports:
      - "9100:9100"

volumes:
  prometheus-volume:
  grafana-volume:
