services:
  iot-monitor:
    image: alexswilliams/homepower:master--2024-08-09-00-07--0365bd9
    volumes:
      - "./config/homepower/devices.yaml:/etc/homepower/devices.yaml"
      - "./config/homepower/credentials.yaml:/etc/homepower/credentials.yaml"
    environment:
      - HOMEPOWER_DEVICE_CONFIG_FILEPATH=/etc/homepower/devices.yaml
      - HOMEPOWER_CREDENTIAL_FILEPATH=/etc/homepower/credentials.yaml
    restart: always
    read_only: true
    logging:
      driver: "local"
      options:
        max-size: "1m"
        max-file: "3"
    ports:
      - "9981:9981"

  govee-monitor:
    image: alexswilliams/govee-prometheus:master--2024-08-09-02-06--e267278
    restart: always
    read_only: true
    logging:
      driver: "local"
      options:
        max-size: "1m"
        max-file: "3"
    volumes:
      - "./config/govee/devices.csv:/etc/govee/devices.csv"
    environment:
      - "BT_ALIASES_FILE_PATH=/etc/govee/devices.csv"
      # - "BLE_SCAN_INTERVAL=53"
      # - "BLE_SCAN_WINDOW=17"
      - "BLE_IGNORE_DUPLICATES=false"
      - "VERBOSE=false"
    network_mode: host # exposes port 8080

  telegraf:
    image: telegraf:1.32.1
    restart: always
    read_only: true
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "9273:9273"
    cap_add:
      - NET_RAW
    volumes:
      - "./config/telegraf.conf:/etc/telegraf/telegraf.conf"
      - "./config/mibs:/root/.snmp/mibs"
      - "/usr/share/snmp/mibs:/usr/share/snmp/mibs"

  prometheus:
    image: prom/prometheus:v2.55.0
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "/mnt/data/prometheus/data:/etc/prometheus/data"
    command:
      - "--storage.tsdb.retention.time=5y"
      - "--storage.tsdb.retention.size=28GB"
      - "--config.file=/etc/prometheus/prometheus.yml"
    expose:
      - "9090"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.3.0
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    volumes:
      - "./config/grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./config/grafana/grafana-datasources/:/etc/grafana/provisioning/datasources"
      - "/mnt/data/grafana:/var/lib/grafana"
    expose:
      - "3000"
    ports:
      - "3000:3000"

  prom-node-exporter:
    image: prom/node-exporter:v1.8.2
    restart: always
    user: root
    privileged: true
    read_only: true
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    pid: host
    volumes:
      - "/proc:/host/proc:ro"
      - "/:/host/root:ro,rslave"
      - "/sys:/host/sys:ro"
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/host/root"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(host/root/)?(dev|proc|sys|run|var/lib/docker/.+)"
      - "--web.listen-address=:9100"
      - "--web.disable-exporter-metrics"
    expose:
      - "9100"
    ports:
      - "9100:9100"
