- name: One Off
  hosts: localhost
  become: true
  tasks:
    - name: Alexw has SSH public keys from github
      authorized_key:
        user: alexw
        state: present
        key: https://github.com/alexswilliams.keys
        exclusive: yes
