global:

route:
  receiver: TG
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1h
  group_by: [alertname]

templates:
  - /etc/alertmanager/config/templates/*.tmpl

receivers:
  - name: TG
    telegram_configs:
      - send_resolved: true
        bot_token_file: /etc/alertmanager/config/bot_token_file.txt
        chat_id: -4782492854
        message: '{{ template "tg.message" . }}'
        # parse_mode: HTML
        # parse_mode: MarkdownV2
        parse_mode: ""
