global:
  scrape_interval: "10s"
  scrape_timeout: "5s"
  evaluation_interval: "30s"

scrape_configs:
  - job_name: prometheus-node-exporter
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
          - prom-node-exporter:9100

  - job_name: laptop-node-exporter
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
          - 192.168.1.18:9100
          - 192.168.1.19:9100

  - job_name: desktop-node-exporter
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
          - 192.168.1.17:9100

  - job_name: router-telegraf
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
          - telegraf:9273

  - job_name: iot-metrics
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
          - iot-monitor:9981

  - job_name: govee-metrics
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
          - 172.18.0.1:8080

storage:
  tsdb:
    out_of_order_time_window: "10s"
