- name: Alexw user exists
  user:
    state: present
    name: alexw
    create_home: yes
    home: /home/alexw
    shell: /bin/bash
- name: Alexw's SSH folder exists
  file:
    state: directory
    path: /home/alexw/.ssh
    owner: alexw
    group: root
    mode: '0750'
- name: Alexw has SSH public keys
  get_url:
    url: https://github.com/alexswilliams.keys
    dest: /home/alexw/.ssh/authorized_keys
    mode: '0400'
    owner: alexw
    backup: yes
- name: Sudo is installed
  pacman:
    state: present
    name: sudo
- name: Alexw is in sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^alexw ALL='
    line: 'alexw ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
