- name: Verify bootstrap
  hosts: archpi
  become: yes
  tasks:
    - name: PACMAN INITIALISED
      include_tasks: ./tasklists/pacman-init.yaml
    - name: CREATE LOCAL USER
      include_tasks: ./tasklists/local-user.yaml
    - name: SUDO CONFIGURED
      include_tasks: ./tasklists/sudo.yaml
    - name: SSH CONFIGURED
      include_tasks: ./tasklists/ssh.yaml
    - name: REMOVE DEFAULT USERS
      include_tasks: ./tasklists/remove-default-users.yaml

- name: Machine Setup
  hosts: archpi
  become: yes
  tasks:
    - name: HOST_BASICS
      include_tasks: ./tasklists/host-basics.yaml
    - name: SYSCTL RULES
      include_tasks: ./tasklists/sysctl-rules.yaml
    - name: FIREWALL
      include_tasks: ./tasklists/firewall.yaml
    - name: MDNS
      include_tasks: ./tasklists/mdns.yaml
    - name: TOOLS
      include_tasks: ./tasklists/tools.yaml
      
