- name: Apply Firewall
  hosts: archpi
  become: true
  tasks:
    - name: FIREWALL
      ansible.builtin.include_tasks: ./tasklists/firewall.yaml
    - name: Firewall restarted
      ansible.builtin.service:
        state: restarted
        name: firewall
