- name: Install ansible
  ansible.builtin.package:
    state: present
    name: ansible

- name: Ansible project directory exists
  ansible.builtin.file:
    state: directory
    path: /opt/ansible
    recurse: true
    owner: root
    group: root
    mode: "0775"

- name: Ansible local task lists are present
  ansible.builtin.copy:
    dest: /opt/
    src: files/ansible
    group: root
    owner: root
    mode: "0664"

- name: Install Ansible Cron (LANG)
  ansible.builtin.cron:
    cron_file: /etc/cron.d/00_ansible
    user: alexw
    env: true
    name: LANG
    job: en_GB.UTF-8

- name: Install Ansible Cron (LC_CTYPE)
  ansible.builtin.cron:
    cron_file: /etc/cron.d/00_ansible
    user: alexw
    env: true
    name: LC_CTYPE
    job: en_GB.UTF-8
    insertafter: LANG

- name: Install Ansible Cron
  ansible.builtin.cron:
    cron_file: /etc/cron.d/00_ansible
    user: alexw
    name: cron playbook
    hour: "1,7,13,19"
    minute: "5"
    job: ansible-playbook ./playbooks/cron-playbook.yaml
