- name: Useful Tools are installed
  ansible.builtin.package:
    state: present
    name:
      - bluez

- name: Bluetooth Daemon started
  ansible.builtin.service:
    name: bluetooth
    state: started
    enabled: true
