- name: Docker is installed
  package:
    state: present
    name:
      - docker
      - btrfs-progs
      - pigz
      - docker-compose

- name: Docker Daemon started
  service:
    name: docker
    state: started
    enabled: yes

- name: Local user is in the docker group
  user:
    name: alexw
    groups: docker
    append: yes

- name: Prune everything
  command:
    cmd: docker system prune --all --volumes --force

- name: Install Prune Cron
  cron:
    cron_file: /etc/cron.d/00_docker
    user: root
    name: prune cron
    minute: "7"
    hour: "10"
    job: "docker system prune --all --volumes --force"
