- name: Docker is installed
  package:
    state: present
    name:
      - docker
      - btrfs-progs
      - pigz
      - docker-compose

- name: Docker Daemon started
  service:
    name: docker
    state: started
    enabled: yes

- name: Python Docker API is present
  pip:
    name: docker

- name: Prune everything
  docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
    builder_cache: yes
