- name: Docker is installed
  package:
    state: present
    name:
      - docker
      - btrfs-progs
      - pigz
      - docker-compose

- name: Docker Daemon started
  service:
    name: docker
    state: started
    enabled: yes

- name: Local user is in the docker group
  user:
    name: alexw
    groups: docker
    append: yes

- name: Python Docker API is present
  pip:
    name: docker

- name: Python Compose API is present
  pip:
    name: compose

- name: Python Docker Compose API is present
  pip:
    name: docker-compose

- name: Prune everything
  docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
    builder_cache: yes
