- name: Docker is installed
  ansible.builtin.package:
    state: present
    name:
      - docker
      - btrfs-progs
      - pigz
      - docker-compose

- name: Docker Daemon started
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Local user is in the docker group
  ansible.builtin.user:
    name: alexw
    groups: docker
    append: true

- name: Prune everything
  ansible.builtin.command:
    cmd: docker system prune --all --volumes --force
  changed_when: true

- name: Install Prune Cron
  ansible.builtin.cron:
    cron_file: /etc/cron.d/00_docker
    user: root
    name: prune cron
    minute: "7"
    hour: "10"
    job: "docker system prune --all --volumes --force"
