- name: Firewall script is configured
  register: firewall_script
  copy:
    dest: /usr/local/bin/firewall.sh
    owner: root
    group: root
    mode: 0755
    content: |
      #!/usr/bin/env bash

      set -e

      iptables -P INPUT ACCEPT
      iptables -P FORWARD ACCEPT
      iptables -P OUTPUT ACCEPT
      ip6tables -P INPUT ACCEPT
      ip6tables -P FORWARD ACCEPT
      ip6tables -P OUTPUT ACCEPT

      iptables -F
      ip6tables -F

      if [ "$1" = 'clear' ]; then
        exit 0
      fi

      iptables -A INPUT -j ACCEPT -m conntrack --ctstate ESTABLISHED,RELATED
      iptables -A INPUT -i lo -j ACCEPT
      iptables -A INPUT -m conntrack --ctstate INVALID -j DROP # Never reject when in invalid state
      iptables -A INPUT -j ACCEPT -p icmp --icmp-type ping -m limit --limit 240/min -s 192.168.1.0/24
      iptables -A INPUT -j ACCEPT -p icmp --icmp-type pong -m limit --limit 240/min

      ip6tables -A INPUT -j ACCEPT -m conntrack --ctstate ESTABLISHED,RELATED
      ip6tables -A INPUT -i lo -j ACCEPT
      ip6tables -A INPUT -m conntrack --ctstate INVALID -j DROP # Never reject when in invalid state
      ip6tables -A INPUT -j ACCEPT -p icmpv6 --icmpv6-type destination-unreachable -m limit --limit 240/min
      ip6tables -A INPUT -j ACCEPT -p icmpv6 --icmpv6-type packet-too-big -m limit --limit 240/min
      ip6tables -A INPUT -j ACCEPT -p icmpv6 --icmpv6-type time-exceeded -m limit --limit 240/min
      ip6tables -A INPUT -j ACCEPT -p icmpv6 --icmpv6-type parameter-problem -m limit --limit 240/min
      ip6tables -A INPUT -j ACCEPT -p icmpv6 --icmpv6-type router-advertisement -m hl --hl-eq 255 -d ff02::1
      ip6tables -A INPUT -j ACCEPT -p icmpv6 --icmpv6-type neighbour-solicitation -m hl --hl-eq 255 -d ff02::/32
      ip6tables -A INPUT -j ACCEPT -p icmpv6 --icmpv6-type neighbour-advertisement -m hl --hl-eq 255 -d fe80::/32 # Only accept advertisments to link local addresses
      ip6tables -A INPUT -j ACCEPT -p icmpv6 --icmpv6-type echo-request -m limit --limit 240/min -s fe80::/32
      ip6tables -A INPUT -j ACCEPT -p icmpv6 --icmpv6-type echo-reply -m limit --limit 240/min

      # Multicast Name Resolution
      iptables -A INPUT -j ACCEPT -p udp --dport 5353 -s 192.168.1.0/24 -d 224.0.0.251 -m comment --comment "mDNS"
      for hoplimit in 1 255; do
        ip6tables -A INPUT -j ACCEPT -p udp --dport 5353 -d ff02::fb -m hl --hl-eq $hoplimit -m comment --comment "mDNS"
      done

      # Perhaps in the future, if we subscribe to LLMNR, these would be useful
      # iptables -A INPUT -j DROP -p udp --dport 5355 -s 192.168.1.0/24 -d 224.0.0.252 -m comment --comment "LLMNR (Windows)"
      # for hoplimit in 1 255; do
      #   ip6tables -A INPUT -j DROP -p udp --dport 5355 -d ff02::1:3 -m hl --hl-eq $hoplimit -m comment --comment "LLMNR (Windows)"
      # done

      # GMP, because we live in a world of multicast now
      iptables -A INPUT -j ACCEPT -s 192.168.1.0/24 -d 224.0.0.0/8 -p igmp
      ip6tables -A INPUT -j ACCEPT -s fe80::/32 -d ff30::/24 -p icmpv6
      ip6tables -A INPUT -j ACCEPT -p icmpv6 --icmpv6-type 143 -s fe80::/32 -d ff02::16 -m hl --hl-eq 1 -m comment --comment "Multicast Listener Reports"

      # RIP
      ip6tables -A INPUT -j ACCEPT -p udp --dport 521 -s fe80::/32 -d ff02::9 -m hl --hl-eq 255 -m comment --comment "RIPng from router"

      # DHCPv6
      ip6tables -A INPUT -j ACCEPT -p udp --dport 546 --sport 547 -s fe80::1:1/32 -m hl --hl-eq 64 -m comment --comment "DHCPv6 from router"


      # Custom rules
      iptables -A INPUT -j ACCEPT -s 192.168.1.0/24 -p tcp --dport 22 -m comment --comment "SSH"
      ip6tables -A INPUT -j ACCEPT -s fe80::/32 -p tcp --dport 22 -m comment --comment "SSH"

      
      # Common drops for the sake of log noise
      iptables -A INPUT -j DROP -p udp -m addrtype --dst-type BROADCAST --dport 9999 -m comment --comment "TPLink Kasa discovery protocol"
      iptables -A INPUT -j DROP -p udp -m addrtype --dst-type BROADCAST --dport 10101 -m comment --comment "Google Home discovery"
      for cmd in iptables ip6tables; do
        $cmd -A INPUT -j DROP -p udp -m multiport --dports 137,138 -m comment --comment "netbios chatter"
        $cmd -A INPUT -j DROP -p udp --dport 17500 -m comment --comment "dropbox chatter"
      done

      iptables -A INPUT -j LOG --log-prefix "[Firewall IPv4] Reject: "
      ip6tables -A INPUT -j LOG --log-prefix "[Firewall IPv6] Reject: "

      # Reject quickly on the local network
      ip6tables -A INPUT -j REJECT -m hl --hl-eq 255 --reject-with icmp6-adm-prohibited

      iptables -A INPUT -j DROP
      iptables -A FORWARD -j DROP
      ip6tables -A INPUT -j DROP
      ip6tables -A FORWARD -j DROP

- name: Firewall is a systemd service
  copy:
    dest: /etc/systemd/system/firewall.service
    owner: root
    group: root
    mode: 0644
    content: |
      [Unit]
      Description=IPTable Reload Script
      After=systemd-networkd.targets

      [Service]
      Type=oneshot
      RemainAfterExit=true
      Restart=no
      User=root
      ExecStart=/usr/bin/env bash /usr/local/bin/firewall.sh up
      ExecReload=/usr/bin/env bash /usr/local/bin/firewall.sh up
      ExecStop=/usr/bin/env bash /usr/local/bin/firewall.sh clear

      [Install]
      WantedBy=multi-user.target

- name: IPTables is installed
  package:
    state: present
    name: iptables

- name: Firewall service is running
  service:
    state: started
    enabled: yes
    name: firewall

- name: Firewall changes are applied
  service:
    state: restarted
    name: firewall
  when: firewall_script.changed
