- name: Firewall script is configured
  register: firewall_script
  copy:
    src: ../files/firewall.sh
    dest: /usr/local/bin/firewall.sh
    owner: root
    group: root
    mode: 0755

- name: Firewall is a systemd service
  copy:
    dest: /etc/systemd/system/firewall.service
    owner: root
    group: root
    mode: 0644
    content: |
      [Unit]
      Description=IPTable Reload Script
      After=network-pre.target
      Wants=network-pre.target

      [Service]
      Type=oneshot
      RemainAfterExit=true
      Restart=no
      User=root
      ExecStart=/usr/bin/env bash /usr/local/bin/firewall.sh up
      ExecReload=/usr/bin/env bash /usr/local/bin/firewall.sh up
      ExecStop=/usr/bin/env bash /usr/local/bin/firewall.sh clear

      [Install]
      WantedBy=multi-user.target

- name: IPTables is installed
  package:
    state: present
    name: iptables

- name: Firewall service is running
  service:
    state: started
    enabled: yes
    name: firewall

- name: Firewall changes are applied
  service:
    state: restarted
    name: firewall
  when: firewall_script.changed
