- name: Base system minimal tools are installed
  ansible.builtin.package:
    state: present
    name:
      - nano
      - less
      - htop
      - lsof
      - lm_sensors

- name: Cron Daemon is installed
  ansible.builtin.package:
    state: present
    name: cronie

- name: PIP is installed
  ansible.builtin.package:
    state: present
    name:
      - python-pip

- name: No MotD
  ansible.builtin.pamd:
    state: absent
    name: system-login
    type: session
    control: optional
    module_path: pam_motd.so

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname_to_set }}"
  when: hostname_to_set is defined

- name: Set timezone to London
  ansible.builtin.timezone:
    name: Europe/London

- name: Configure systemd timesyncd
  register: timesyncd_config
  ansible.builtin.copy:
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      [Time]
      NTP=uk.pool.ntp.org
      RootDistanceMaxSec=5
      PollIntervalMinSec=3600
      PollIntervalMaxSec=86400

- name: Apply timesyncd changes
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted
  when: timesyncd_config.changed

- name: Use fake hw clock if needed
  ansible.builtin.package:
    name: fake-hwclock
    state: present
  when: no_hw_clock is defined

- name: Enable fake-hwclock service
  ansible.builtin.service:
    name: fake-hwclock
    state: started
    enabled: true
  when: no_hw_clock is defined

- name: Generate GB locale
  community.general.locale_gen:
    name: en_GB.UTF-8
    state: present

- name: Configure systemd journald
  register: journald_config
  ansible.builtin.copy:
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      [Journal]
      Storage=volatile
      Compress=4K
      Seal=no
      SplitMode=none
      RuntimeMaxUse=16M
      ForwardToSyslog=no
      ForwardToKMsg=no
      ForwardToConsole=no
      ForwardToWall=yes
      MaxLevelStore=notice
      MaxLevelWall=warning
      ReadKMsg=no
      Audit=no

- name: Apply systemd journald config
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
  when: journald_config.changed

- name: Old Journald Folder does not exist
  ansible.builtin.file:
    path: /var/log/journal
    state: absent
