- name: Alexw user exists
  user:
    state: present
    name: alexw
    create_home: yes
    home: /home/alexw
    shell: /bin/bash

- name: Alexw's SSH folder exists
  file:
    state: directory
    path: /home/alexw/.ssh
    owner: alexw
    group: alexw
    mode: 0700

- name: Alexw has SSH public keys from github
  authorized_key:
    user: alexw
    state: present
    key: https://github.com/alexswilliams.keys
    exclusive: yes

- name: Alexw bashrc is configured
  copy:
    dest: /home/alexw/.bashrc
    group: alexw
    owner: alexw
    mode: 0644
    content: |
      export EDITOR=nano
      export PAGER=less
      [[ $- != *i* ]] && return
      alias ls='ls --color=auto'
      PS1='[\u@\h \W]\$ '
    validate: "/bin/bash %s"

- name: SSH ControlMasters directory exists
  file:
    state: directory
    path: /home/alexw/.ssh/controlmasters
    recurse: yes
    owner: alexw
    group: alexw
    mode: 0770

- name: Alexw ssh config is configured
  copy:
    dest: /home/alexw/.ssh/config
    group: alexw
    owner: alexw
    mode: 0664
    content: |
      Host *
        ControlPath ~/.ssh/controlmasters/%r@%h:%p
        ControlMaster auto
        ControlPersist 2m

- name: ProcPS Config directory exists
  file:
    state: directory
    path: /home/alexw/.config/procps
    recurse: yes
    owner: alexw
    group: alexw
    mode: 0770

- name: Alexw toprc is configured
  copy:
    dest: /home/alexw/.config/procps/toprc
    src: ../files/toprc
    group: alexw
    owner: alexw
    mode: 0644
