- name: mDNS packages are installed
  package:
    state: present
    name:
      - avahi
      - nss-mdns

- name: Avahi configured
  register: avahi_daemon_config
  copy:
    dest: /etc/avahi/avahi-daemon.conf
    owner: root
    group: root
    mode: 0644
    content: |
      [SERVER]
      domain-name=local
      use-ipv4=yes
      use-ipv6=yes
      allow-interfaces=eth0
      use-iff-running=yes
      # Required so that systemd can work out if it started or not
      enable-dbus=yes
      disallow-other-stacks=yes
      allow-point-to-point=no
      cache-entries-max=2048
      ratelimit-interval-usec=10000
      ratelimit-burst=20
      
      [WIDE-AREA]
      enable-wide-area=no
      
      [PUBLISH]
      disable-publishing=no
      disable-user-service-publishing=no
      add-service-cookie=yes
      publish-addresses=yes
      publish-hinfo=no
      publish-workstation=no
      publish-domain=yes
      publish-resolv-conf-dns-servers=no
      publish-aaaa-on-ipv4=yes
      publish-a-on-ipv6=no
      
      [REFLECTOR]
      enable-reflector=no
      
      [RLIMITS]
      rlimit-core=0
      rlimit-fsize=0
      rlimit-nofile=30
      rlimit-nproc=3

- name: SSH Service Published on mDNS
  register: ssh_mdns_service
  copy:
    dest: /etc/avahi/services/ssh.service
    owner: root
    group: root
    mode: 0644
    content: |
      <service-group>
        <name replace-wildcards="yes">%h</name>
        <service>
          <type>_ssh._tcp</type>
          <port>22</port>
        </service>
      </service-group>


- name: SystemD ResolveD service is disabled
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
    masked: yes

- name: SystemD ResolveD (DBUS) service is disabled
  systemd:
    name: dbus-org.freedesktop.resolve1
    state: stopped
    enabled: no
    masked: yes

- name: Avahi Daemon changes are applied
  service:
    state: restarted
    enabled: yes
    name: avahi-daemon
  when: avahi_daemon_config.changed or ssh_mdns_service.changed

- name: mDNS Config Set
  copy:
    dest: /etc/mdns.allow
    owner: root
    group: root
    mode: 0644
    content: |
      .local.
      .local

- name: Hosts File Set
  copy:
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
    content: |
      # No static entries

- name: Resolv Conf Set
  copy:
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
    content: |
      nameserver 2606:4700:4700::1001
      nameserver 2001:4860:4860::8844
      nameserver 2606:4700:4700::1111
      nameserver 2001:4860:4860::8888
      nameserver fe80::1:1%eth0
      nameserver 1.0.0.1
      nameserver 8.8.4.4
      nameserver 1.1.1.1
      nameserver 8.8.8.8
      nameserver 192.168.1.1
      search local home.alexswilliams.co.uk alexswilliams.co.uk
      options ndots:1
      options timeout:1
      options attempts:1
      options edns0

- name: GAI Config Set
  copy:
    dest: /etc/gai.conf
    owner: root
    group: root
    mode: 0644
    content: |
      reload no
      
      # Desirable:
      # Loopback
      precedence ::1/128 100
      # Link Local
      precedence fe80::/10 50
      # Benchmarking route
      precedence 2001:2::/48 45
      # ANYWHERE ELSE
      precedence ::/0 40
      
      # Undesirable:
      # 6to4
      precedence 2002::/32 20
      # Teredo
      precedence 2001::/16 10
      # NAT64
      precedence 64:ff9b::/96 9
      # 6over4
      precedence fe80::/96 8
      # ipv4-mapped
      precedence ::ffff:0:0/96 7
      # ipv4-translated
      precedence ::ffff:0:0:0/96 6
      # discardable - don't prefer black hole addresses
      precedence 100::/64 5
      # documentation - possible misconfiguration
      precedence 2001:db8::/32 4
      # site-local, if you can work out what that means
      precedence fec0::/10 2

- name: NSSwitch Hosts Entry Configured
  lineinfile:
    path: /etc/nsswitch.conf
    state: present
    insertbefore: EOF
    regex: '^hosts: '
    line: "hosts: myhostname files mdns_minimal [NOTFOUND=return] dns mdns"
