- name: Alexw user exists
  ansible.builtin.user:
    state: present
    name: alexw
    create_home: true
    home: /home/alexw
    shell: /bin/bash

- name: Alexw's SSH folder exists
  ansible.builtin.file:
    state: directory
    path: /home/alexw/.ssh
    owner: alexw
    group: alexw
    mode: "0700"

# TODO: work out why this fails during bootstrap?
# - name: Alexw has SSH public keys from github
#   ansible.posix.authorized_key:
#     user: alexw
#     state: present
#     key: https://github.com/alexswilliams.keys
#     exclusive: true

- name: Alexw bashrc is configured
  ansible.builtin.copy:
    dest: /home/alexw/.bashrc
    group: alexw
    owner: alexw
    mode: "0644"
    content: |
      export EDITOR=nano
      export PAGER=less
      export LANG=en_GB.UTF-8
      export LC_CTYPE=en_GB.UTF-8
      [[ $- != *i* ]] && return
      alias ls='ls --color=auto'
      PS1='[\u@\h \W]\$ '
    validate: "/bin/bash %s"

- name: SSH ControlMasters directory exists
  ansible.builtin.file:
    state: directory
    path: /home/alexw/.ssh/controlmasters
    recurse: true
    owner: alexw
    group: alexw
    mode: "0770"

- name: Alexw ssh config is configured
  ansible.builtin.copy:
    dest: /home/alexw/.ssh/config
    group: alexw
    owner: alexw
    mode: "0664"
    content: |
      Host *
        ControlPath ~/.ssh/controlmasters/%r@%h:%p
        ControlMaster auto
        ControlPersist 2m

- name: ProcPS Config directory exists
  ansible.builtin.file:
    state: directory
    path: /home/alexw/.config/procps
    recurse: true
    owner: alexw
    group: alexw
    mode: "0770"

- name: Alexw toprc is configured
  ansible.builtin.copy:
    dest: /home/alexw/.config/procps/toprc
    src: files/toprc
    group: alexw
    owner: alexw
    mode: "0644"
