- name: Monitoring project directory exists
  ansible.builtin.file:
    state: directory
    path: /opt/monitoring
    recurse: true
    owner: alexw
    group: alexw
    mode: "0775"

- name: Monitoring compose project is configured
  ansible.builtin.copy:
    dest: /opt/
    src: files/monitoring
    group: alexw
    owner: alexw
    mode: "0664"

- name: SNMP and ethtool are installed
  ansible.builtin.package:
    state: present
    name:
      - net-snmp
      - ethtool

- name: All containers are started
  ansible.builtin.command:
    chdir: /opt/monitoring
    cmd: docker compose up --build --detach --no-color --pull missing --quiet-pull --remove-orphans
  changed_when: true

- name: Prometheus has been reloaded
  changed_when: true
  ansible.builtin.uri:
    url: http://localhost:9090/-/reload
    method: POST
    return_content: false
    status_code:
      - 200

- name: Alertmanager has been reloaded
  changed_when: true
  ansible.builtin.uri:
    url: http://localhost:9093/-/reload
    method: POST
    return_content: false
    status_code:
      - 200
