- name: Pacman keyring initialised
  ansible.builtin.command:
    cmd: pacman-key --init
    creates: /etc/pacman.d/gnupg
  register: pacman_keyring_initialised

- name: Pacman keyring populated with archlinuxarm
  ansible.builtin.command:
    cmd: pacman-key --populate archlinuxarm
  when: pacman_keyring_initialised.changed
  changed_when: true
