- name: Alarm user removed
  ansible.builtin.user:
    state: absent
    name: alarm

- name: Alarm user's home dir removed
  ansible.builtin.file:
    state: absent
    path: /home/alarm

- name: Lock root user
  ansible.builtin.user:
    state: present
    name: root
    password_lock: true
