- name: Sudo is installed
  package:
    state: present
    name: sudo

- name: Sudoers is set up
  copy:
    dest: /etc/sudoers
    group: root
    owner: root
    mode: 0440
    content: |
      Defaults env_keep += "EDITOR PAGER LANG LANGUAGE LC_*"
      root  ALL=(ALL) ALL
      alexw ALL=(ALL) NOPASSWD: ALL
    validate: "/usr/sbin/visudo -cf %s"

- name: Remove sudoers directory
  file:
    state: absent
    path: /etc/sudoers.d

- name: TEST Root and alexw can both sudo successfully
  shell: "sudo -u alexw echo test && sudo -u alexw sudo echo test"
  args:
    warn: no
  register: sudo_works
  changed_when: false
  failed_when: sudo_works.rc != 0
